Revert OpenCV version change
tenstorrent/tt-forge-fe pull request #706
Opened 2024-11-14 08:03 UTC by ashokkumarkannan1

Fix: https://github.com/tenstorrent/tt-forge-fe/issues/703

Previously CI was blocked with `ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.` issue. As per the suggestion [here](https://github.com/opencv/opencv-python/issues/680), downgraded the `opencv-python-headless` version from `4.6.0.66` to `4.5.5.64` in this [PR](https://github.com/tenstorrent/tt-forge-fe/pull/666).

Now this was blocking the MNIST Model with this [issue](https://github.com/tenstorrent/tt-forge-fe/issues/703). Hence reverting this change to see whether it still affect the CI.

2024-11-14 09:15 UTC, dgolubovicTT approved these changes

2024-11-14 14:14 UTC, nvukobratTT commented
@gfengTT @ashokkumarkannan1 can we try to use some newer version of OpenCV that doesn't hit this issue? 

This more seems like bug in one of their version, so let's just test out newer one and see will that fix the issue, rather than downgrading it back again :))

_Note: [Here](https://github.com/facebookresearch/nougat/issues/40) is an example of a similar failure. I'm not sure if it's the same issues, but let's try to keep our libraries on newer versions, rather than downgrading them :))_

2024-11-14 14:15 UTC, nvukobratTT requested changes
@gfengTT @ashokkumarkannan1 can we try to use some newer version of OpenCV that doesn't hit this issue? 

This more seems like bug in one of their version, so let's just test out newer one and see will that fix the issue, rather than downgrading it back again :))

_Note: [Here](https://github.com/facebookresearch/nougat/issues/40) is an example of a similar failure. I'm not sure if it's the same issues, but let's try to keep our libraries on newer versions, rather than downgrading them._

2024-11-14 15:08 UTC, ashokkumarkannan1 commented
> @gfengTT @ashokkumarkannan1 can we try to use some newer version of OpenCV that doesn't hit this issue?
> 
> This more seems like bug in one of their version, so let's just test out newer one and see will that fix the issue, rather than downgrading it back again :))
> 
> _Note: [Here](https://github.com/facebookresearch/nougat/issues/40) is an example of a similar failure. I'm not sure if it's the same issues, but let's try to keep our libraries on newer versions, rather than downgrading them._


I agree with your point @nvukobratTT . From this [Release History](https://pypi.org/project/opencv-python-headless/#history) page, it seems `4.10.0.84` is the latest stable version. I will update this change here in this PR to verify is there any CI failures here. 

@gfengTT  Can you please confirm from your side whether `4.10.0.84` version works from your side?

2024-11-14 16:12 UTC, gfengTT commented
Great suggestion @nvukobratTT . 

@ashokkumarkannan1 Confirming `4.10.0.84` works.

2024-11-15 11:17 UTC, nvukobratTT commented
@ashokkumarkannan1 make sure to update PR name to reflect new changes :))

2024-11-15 11:18 UTC, nvukobratTT approved these changes

2024-11-15 11:57 UTC, merged