Remove transpose cast to float32 and update test_transpose
tenstorrent/tt-forge-fe pull request #719
Opened 2024-11-15 16:53 UTC by dgolubovicTT

Closes #690.
Changes in this PR:

1. Remove transpose output cast to float32 and transpose op argument data_format. Transpose shouldn't have data_format attribute! It should give the same data_format on output as it gets on input.
2. Update test_transpose to vary between torch.float32 and torch.bfloat16 inputs. 
3. Caught tensor mismatch for transpose when using torch.bfloat16 inputs, and marked as xfail untill resolved on metal side.

Effort to test transpose on bfloat16 inputs emerges from the need to run Llama 3B on bfloat16 since embedding only has support for bfloat16.

2024-11-15 17:12 UTC, nvukobratTT reviewed
Seems like you have some unexpected changes on this PR. Can you double check?

2024-11-15 17:39 UTC, dgolubovicTT commented
Wow, yeah... Addressing

2024-11-16 11:16 UTC, nvukobratTT approved these changes

2024-11-16 11:16 UTC, nvukobratTT commented on forge/test/mlir/test_ops.py
> +    framework_model = Transpose(dims).to(data_format)
Do we need to push the model to the desired DF if is already applied to input?

2024-11-16 11:18 UTC, nvukobratTT requested changes
Accidently approved.. Seems like push CI is failing. Can you check if there are few more places where transpose attribute needs to be updated?

2024-11-18 09:38 UTC, dgolubovicTT commented
Yeah, tvm_to_python had created the Transpose op arguments with out_dtype. Addressed now.

2024-11-18 11:30 UTC, nvukobratTT approved these changes

2024-11-18 14:14 UTC, merged