Convert flatbuffer binary to json
tenstorrent/tt-forge-fe pull request #835
Opened 2024-12-04 12:23 UTC by meenakshiramanathan1

2024-12-05 12:03 UTC, dgolubovicTT approved these changes

2024-12-13 11:14 UTC, pilkicTT requested changes
Why is this needed? We are already saving the generated TTNN IR with other reports in default reportify directory...

2024-12-17 07:53 UTC, meenakshiramanathan1 commented
> Why is this needed? We are already saving the generated TTNN IR with other reports in default reportify directory...

This was added as a way to dump the generated binary and json so that it can be used to run generate_md script present in [this](https://github.com/tenstorrent/tt-torch/tree/dgolubovic/check-parsing-form-to-json) branch as an experiment.

CC: @dgolubovicTT

2024-12-20 12:29 UTC, nvukobratTT commented
@meenakshiramanathan1 @dgolubovicTT can you share a bit more details about this PR? 

Is this for temporary usage, or do you see the value of making this production-ready for future use? If that is the case, please provide details as to why, and if can we align it with the current logic for storing TTIRs.

2024-12-23 11:30 UTC, dgolubovicTT commented
This change was made in order to generate json files for unique ops so that we could generate ttnn configurations for the ttnn folks. @tt-mpantic contacted me to check if this json generation works as input to [generate_md.py ](https://github.com/tenstorrent/tt-torch/blob/main/tt_torch/tools/generate_md.py) script for generating ttnn configurations. I verified that it had worked and generated ttnn configurations Mladen needed. 

If we are going to provide those configurations to ttnn folks, we should have this in main... Question for @tt-mpantic: Is this recurring and can you give more details on that ttnn effort? Are they using these for debugging, planning or something else?

2024-12-23 17:25 UTC, nvukobratTT commented
> recurring and can you give more details on that ttnn effort? Are they using these for debugging, planning or something

Thanks for the context! 

The information you shared, this will be valuable information to have for the long run. I.e. to have this data stored in our database. Let's discuss the details tomorrow and determine next steps :))

2025-04-17 07:10 UTC, closed without merging